### ISSUE TITLE
Menu item (sidebar) is not active.

### ISSUE THREAD

**Issue by multiarts** [jeroennoten/Laravel-AdminLTE#612] opened 2020-05-31 02:29 UTC
Menu item (sidebar) is not active, on localhost it is active, but on the web server (heroku for testing) no, the active class is not added.
Laravel 7.x, AdminLTE 3.2
<img src="https://i.imgur.com/CDxBegN.png" />

**Comment by lacodimizer** [comment] 2020-06-04 14:33
@multiarts Which Laravel version and which project version do you use?

**Comment by multiarts** [comment] 2020-06-04 14:58
7.x

**Comment by lacodimizer** [comment] 2020-06-20 20:25
@multiarts is the issue actual?

**Comment by multiarts** [comment] 2020-06-27 17:10
> @multiarts is the issue actual?

Yes.

**Comment by Shidersz** [comment] 2020-06-27 19:06
Can you provide more information:
1) Do you see any error in the **Browser's Console** or **Network** tabs (using the web developers tools)
2) When you click a menu link (for example `Todos` in your image), what is the URL you see in the browser on local development and what is the one you see in the Heroku web server?
3) Are you using the same `adminlte.php` config file on local development and Heroku web server?

**Comment by lacodimizer** [comment] 2020-06-27 19:10
I think it‘s an issue on your local env, for example, the htaccess rules are not correct. I don‘t can find any error on any browsers and webservers.

**Comment by ivarsju** [comment] 2020-06-30 15:31
> I think it‘s an issue on your local env, for example, the htaccess rules are not correct. I don‘t can find any error on any browsers and webservers.

he told that on localhost it is active on server it is not.

The same for me, I had laravel 6.x now upgraded to 7.x (v7.14.1) and jeroennoten/laravel-adminlte v3.3.1 (the same problem existed in older version, for example v3.2.0).

I have 3 setups - local, stage and prod. Active menu works as expected on local and stage, but active class is never added on prod. Only prod is https, local and stage is http - my guess is it is related but I am not sure.

**Comment by Shidersz** [comment] 2020-06-30 17:16
Hi @ivarsju , can you give a try to `dev-master` version of the package?

**1)** Edit the `composer.json` file of your Laravel project and use `"jeroennoten/laravel-adminlte": "dev-master"` on the **require** section instead of the current one.

**2)** Run the `composer update` command.

Also, can you give an example of how are you defining the menu item configuration that is not active on production when you click on it.

**Comment by ivarsju** [comment] 2020-07-01 15:27
I was not able to just update the composer, I had to update views and config too. But still not working, active class is never added.
I have one small project, good for testing. Menu config is just:
return [
    [
        'text' => 'Video',
        'url'  => 'video',
        'icon' => 'nav-icon fas fa-video'
    ],
];

And in AppServiceProvider:
    public function boot(Dispatcher $events, Repository $config)
    {
        if ($config->get('app.env') === 'prod') {
            \URL::forceScheme('https');
        }

        $events->listen(BuildingMenu::class, function (BuildingMenu $event) use ($config) {
            call_user_func_array([$event->menu, 'add'], $config->get('menu', []));
        });
    }

In http://stage.my.site.com/video the menu item is active, in https://my.site.com/video it is not.
The same issue in another project with similar setup (but more menu items).

**Comment by Shidersz** [comment] 2020-07-01 17:20
Thanks for your feedback @ivarsju , I manage to reproduce the issue, comes mainly for the usage of `URL::forceScheme('https');`. I'm preparing a fix for this issue, but I will like that you test it before uploading. So can you make the next change on the `dev-master` version of this package:

On your local project, edit the file `vendor/jeroennoten/laravel-adminlte/src/Menu/ActiveChecker.php` and replace the method `checkPattern()` by the **new version**:

### Old Version

```php
/**
 * Checks if an url pattern matches the requested url.
 *
 * @param string $pattern
 * @return bool
 */
 protected function checkPattern($pattern)
{
    // First, check if the pattern is a regular expression.

    if (Str::startsWith($pattern, 'regex:')) {
        $regex = Str::substr($pattern, 6);

        return (bool) preg_match($regex, $this->request->path());
    }

    // If pattern is not a regex, check if the requested url matches the
    // absolute path to the given pattern.

    return Str::is($this->url->to($pattern), $this->request->url());
}
```
### New Version

```php
/**
 * Checks if an url pattern matches the requested url.
 *
 * @param string $pattern
 * @return bool
 */
protected function checkPattern($pattern)
{
    // First, check if the pattern is a regular expression.

    if (Str::startsWith($pattern, 'regex:')) {
        $regex = Str::substr($pattern, 6);

        return (bool) preg_match($regex, $this->request->path());
    }

    // If pattern is not a regex, check if the requested url matches the
    // absolute path to the given pattern.

    $pattern = preg_replace('(^https?://)', "", $this->url->to($pattern));
    $request = preg_replace('(^https?://)', "", $this->request->url());
    return Str::is($pattern, $request);
}
```

**Comment by lacodimizer** [comment] 2020-07-01 17:47
@Shidersz What do you think about this version? 

```php
/**
 * Checks if an url pattern matches the requested url.
 *
 * @param string $pattern
 * @return bool
 */
protected function checkPattern($pattern)
{
    // First, check if the pattern is a regular expression.

    if (Str::startsWith($pattern, 'regex:')) {
        $regex = Str::substr($pattern, 6);

        return (bool) preg_match($regex, $this->request->path());
    }

    // If pattern is not a regex, check if the requested url matches the
    // absolute path to the given pattern.

    return Str::is($this->url->to($pattern), $this->request->path());
}
```

**Comment by Shidersz** [comment] 2020-07-01 18:20
@lacodimizer That fails on some of the test we have. However, we can try to get a short version once they can confirm the issue is solved this way. The main problem I have observed (on my local environment) is that when you use `URL::forceScheme('https')` the method `$this->url->to($pattern)` always use the `https` scheme to generate the url, while `$this->request->url()` sometimes uses the `http` scheme and that causes the issue.

**Comment by lacodimizer** [comment] 2020-07-01 18:39
@Shidersz You are right with the tests...

**Comment by Shidersz** [comment] 2020-07-01 19:37
@lacodimizer In case you need a test to reproduce the issue with the current implementation, you can use next changes:

**1)** Change next methods of `tests/TestCase.php` like this:

```php
protected function makeActiveChecker($uri = 'http://example.com', $scheme = null)
{
    return new ActiveChecker(
        $this->makeRequest($uri),
        $this->makeUrlGenerator($uri, $scheme)
    );
}

protected function makeUrlGenerator($uri = 'http://example.com', $scheme = null)
{
    $UrlGenerator = new UrlGenerator(
        $this->getRouteCollection(),
        $this->makeRequest($uri)
    );

    if ($scheme) {
        $UrlGenerator->forceScheme($scheme);
    }

    return $UrlGenerator;
}
```

**2)** Add the next new test to `tests/Menu/ActiveCheckerTest.php` file:

```php
public function testWithForcedScheme()
{
    $checker = $this->makeActiveChecker('http://example.com/about', 'https');

    $isActive = $checker->isActive(['url' => 'about']);
    $this->assertTrue($isActive);

    $isActive = $checker->isActive(['url' => 'http://example.com/about']);
    $this->assertTrue($isActive);

    $isActive = $checker->isActive(['url' => 'https://example.com/about']);
    $this->assertTrue($isActive);
}
```

Also, we don't even need to inject `Request` into the `ActiveChecker` constructor, we can access the request using the `UrlGenerator` instance as:

```php
$this->url->getRequest()
```

**Comment by ivarsju** [comment] 2020-07-02 14:08
> Thanks for your feedback @ivarsju , I manage to reproduce the issue, comes mainly for the usage of `URL::forceScheme('https');`. I'm preparing a fix for this issue, but I will like that you test it before uploading. So can you make the next change on the `dev-master` version of this package:
> 
> On your local project, edit the file `vendor/jeroennoten/laravel-adminlte/src/Menu/ActiveChecker.php` and replace the method `checkPattern()` by the **new version**:
> 
> ### Old Version
> ```
> /**
>  * Checks if an url pattern matches the requested url.
>  *
>  * @param string $pattern
>  * @return bool
>  */
>  protected function checkPattern($pattern)
> {
>     // First, check if the pattern is a regular expression.
> 
>     if (Str::startsWith($pattern, 'regex:')) {
>         $regex = Str::substr($pattern, 6);
> 
>         return (bool) preg_match($regex, $this->request->path());
>     }
> 
>     // If pattern is not a regex, check if the requested url matches the
>     // absolute path to the given pattern.
> 
>     return Str::is($this->url->to($pattern), $this->request->url());
> }
> ```
> 
> ### New Version
> ```
> /**
>  * Checks if an url pattern matches the requested url.
>  *
>  * @param string $pattern
>  * @return bool
>  */
> protected function checkPattern($pattern)
> {
>     // First, check if the pattern is a regular expression.
> 
>     if (Str::startsWith($pattern, 'regex:')) {
>         $regex = Str::substr($pattern, 6);
> 
>         return (bool) preg_match($regex, $this->request->path());
>     }
> 
>     // If pattern is not a regex, check if the requested url matches the
>     // absolute path to the given pattern.
> 
>     $pattern = preg_replace('(^https?://)', "", $this->url->to($pattern));
>     $request = preg_replace('(^https?://)', "", $this->request->url());
>     return Str::is($pattern, $request);
> }
> ```

Yes, it has fixed active menu issue

**Comment by Shidersz** [comment] 2020-07-02 16:35
Nice, thanks for your help @ivarsju , this issue should be solved on the next releases.

**Comment by ivarsju** [comment] 2020-07-03 08:17
Than you!

**Comment by lacodimizer** [comment] 2020-07-03 14:54
@ivarsju @Shidersz the release v3.4.0 is out now.

**Closed by lacodimizer** 2020-07-03 14:54 UTC
Labels: scheduled

**Comment by multiarts** [comment] 2020-07-05 22:41
I'm sorry I didn't answer, I was sick.
Now with the update from 3.3 to 3.4 the failure has been resolved.
Thank you very much.
