### ISSUE TITLE
the menu remains active 

### ISSUE THREAD

**Issue by balinux** [jeroennoten/Laravel-AdminLTE#814] opened 2021-02-25 06:55 UTC
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | v7.27.0
| Project Version         | ^3.5

### Current Behavior

Currently the menu role-example remains active even when the URL is different

![image](https://user-images.githubusercontent.com/10473273/109113770-b962b700-7777-11eb-9eb3-6e2a64f10f8f.png)

user link : http://udayana-mall.test/rbac/user

role-example link: http://udayana-mall.test/rbac/roles

### Expected Behavior

role-example is not active when opening another menu

### Steps to Reproduce

I've done this configuration, but still can't

                [
                    'text' => 'Role-example',
                    'url'  => 'rbac/roles',
                    'active' => ['rbac/roles'],
                    'icon' => 'fas fa-fw fa-address-card',
                ],

**Comment by Shidersz** [comment] 2021-02-25 13:41
Hi @balinux , on the image you have upload, the menu item `Role-example` is not active when the **url** is **udayana-mall.test/rbac/user**. Can you upload a picture where the problem appears? Also share the full menu configuration.

**Comment by Shidersz** [comment] 2021-03-04 00:16
@resslinger You can close this one, no feedback from user...

**Comment by balinux** [comment] 2021-03-04 02:50
hi @Shidersz sorry for slow response

this is my full menu configuration

```
    'menu' => [
        [
            'text' => 'search',
            'search' => false,
            'topnav' => true,
        ],
        [
            'text' => 'blog',
            'url'  => 'admin/blog',
            'can'  => 'manage-blog',
        ],
        ['header' => 'account_settings'],
        [
            'text' => 'Products',
            'url'  => 'admin/product',
            'icon' => 'fas fa-fw fa-store',
            'submenu' => [
                [
                    'text' => 'Tambah Produk',
                    'url'  => 'admin/product/add',
                ],
                [
                    'text' => 'Daftar Produk',
                    'url'  => 'admin/product',
                ],
      
            ]
        ],
        [
            'text' => 'Kategori',
            'url'  => 'admin/category',
            'icon' => 'fas fa-fw fa-menu',
            'submenu' => [
                // [
                //     'text' => 'Tambah kategori',
                //     'url'  => 'admin/category/create',
                // ],
                [
                    'text' => 'Daftar kategori',
                    'url'  => 'admin/category',
                ],
            ]
        ],
        [
            'text' => 'RBAC',
            'url'  => 'rbac/user',
            'icon' => 'fas fa-fw fa-users',
            'submenu' => [
                [
                    'text' => 'User',
                    'url'  => 'rbac/user',
                    'icon' => 'fas fa-fw fa-user',
                ],
                // [
                //     'text' => 'Role',
                //     'url'  => 'rbac/roles',
                //     'icon' => 'fas fa-fw fa-address-card',
                // ],
                [
                    'text' => 'Role-example',
                    'url'  => 'rbac/roles',
                    'active' => ['rbac/roles'],
                    'icon' => 'fas fa-fw fa-address-card',
                ],
            ]
        ],
        [
            'text' => 'profile',
            'url'  => 'user/profile',
            'icon' => 'fas fa-fw fa-user',
        ],
        [
            'text' => 'Toko',
            'url'  => 'store',
            'icon' => 'fas fa-fw fa-store',
        ],
    ],

```

**Comment by Shidersz** [comment] 2021-03-04 12:48
@balinux Please, add the next data:

1. Steps to reproduce the issue (what menu item you click and which one remains active after the click).
2. An image showing the situation (since your original image do not show any issue).

Thanks!

**Comment by Shidersz** [comment] 2021-03-18 16:22
No feedback from user since 2 weeks...

**Closed by Shidersz** 2021-03-18 16:22 UTC
Labels: waiting for infos
