### ISSUE TITLE
ISSUE: control sidebar(right sidebar) push (data-slide="false") not works.

### ISSUE THREAD

**Issue by jrserrano** [jeroennoten/Laravel-AdminLTE#335] opened 2019-08-01 16:08 UTC
Hi everyone:
I´m stuck with the right sidebar, control-sidebar, using:

`<a href="#" data-toggle="control-sidebar" data-slide="false">Toggle Control Sidebar</a>`

makes the toggle doesn´t work, the right side bar doesn´t appear, and without data-slide = "false", the control sidebar always slide over the content.

and changing in adminlte.js in line 320 :
`var Default = {
    slide: false
  }`
it doesnt work too.

Any help.

Thanks a lot.

**Comment by lacodimizer** [comment] 2019-08-06 07:25
@jrserrano Which version of this project do you use?

**Comment by jrserrano** [comment] 2019-08-06 07:43
The 1.25.1 release, i installed it as it is indicated in the Readme.md with the last version of Laravel 5.8.16

**Comment by lacodimizer** [comment] 2019-08-06 09:38
Please test it with the latest pre-release version von 1.26.x.

**Comment by jrserrano** [comment] 2019-08-06 14:52
I tested it with the pre-release 1.26 and still doesn´t push, with data-slide = "false" or changing in the adminlte.js slide to false, always slide over the content.

**Comment by lacodimizer** [comment] 2019-08-07 07:36
@REJack any idea?

**Comment by REJack** [comment] 2019-08-07 08:26
I've checked the code, it always slides since there is a transition in the css but also there is an bug in the JS caused by bootstrap's JS we can't use `data-slide` anymore I'll rename this to `data-controlsidebar-slide` to avoid the js error.

I'll fix this issue soon.

**Comment by REJack** [comment] 2019-08-13 11:07
@lacodimizer I've released AdminLTE v2.4.16, with this fix and some other changes/fixes😄

**Comment by lacodimizer** [comment] 2019-08-27 09:12
The v1.27.0-pre was released with this fix.

**Comment by jrserrano** [comment] 2019-08-27 15:13
I have tested with this pre-release 1.27, and it works, and it is much better with the configuration of this right sidebar added to adminlte.php.
Thanks

**Closed** 2019-08-28 07:18 UTC
