### ISSUE TITLE
updating to 3.4

### ISSUE THREAD

**Issue by gildastema** [jeroennoten/Laravel-AdminLTE#654] opened 2020-07-04 11:50 UTC
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 7
| Project Version         |3.4

### Current Behavior
ErrorException
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist. (View: /mnt/c/Users/HP/code/Beehive/kiper-dash/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php) (View: /mnt/c/Users/HP/code/Beehive/kiper-dash/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php) (View: 

ErrorException
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist. (View: /mnt/c/Users/HP/code/Beehive/kiper-dash/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php) (View: /mnt/c/Users/HP/code/Beehive/kiper-dash/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php) (View: 
### Steps to Reproduce

update to 3.3 to 3.4 

![image](https://user-images.githubusercontent.com/19803232/86511855-3f9f4700-bdfd-11ea-8da5-f397c1351a1b.png)

**Comment by REJack** [comment] 2020-07-04 14:01
Duplicate of #652

**Closed** 2020-07-04 14:21 UTC
