### ISSUE TITLE
Undefined index: icon

### ISSUE THREAD

**Issue by mxhunter** [jeroennoten/Laravel-AdminLTE#47] opened 2016-11-29 21:42 UTC
After install 

ErrorException in 9dcf61b8761ef39af9d88755df9f76b70b292f8d.php line 8:
Undefined index: icon (View: a/p/p/p/a/t/h/resources\views\vendor\adminlte\partials\menu-item.blade.php) (View: a/p/p/p/a/t/h/resources\views\vendor\adminlte\partials\menu-item.blade.php) (View: a/p/p/p/a/t/h/resources\views\vendor\adminlte\partials\menu-item.blade.php) (View: a/p/p/p/a/t/h/resources\views\vendor\adminlte\partials\menu-item.blade.php)

**Comment by fryiee** [comment] 2016-11-30 08:28
Same issue here. Looks to be an issue with the latest update breaking font awesome icons on the menu. I got around it (for now) by making sure all non-header menu items explicitly had an icon set (even though they still dont show up).

**Comment by mxhunter** [comment] 2016-11-30 15:21
any work around for override this ?

**Comment by fryiee** [comment] 2016-11-30 15:41
As said above, if you don't mind the icons not showing, just explicitly set icons for all menu items, eg:
`
'menu' => [
        [
          'text' => 'Users',
            'url' => 'admin/user',
            'icon' => '',
        ],
        [
            'text' => 'Competitions',
            'url'  => 'admin/comp',
            'icon' => '',
        ],
    ],
`

**Comment by jeroennoten** [comment] 2016-11-30 15:45
Hmm strange. The template has `{{ $item['icon'] or 'circle-o' }}`, which is a Blade shorthand for `{{ isset($item['icon']) ? $item['icon'] : 'circle-o' }}` (see https://laravel.com/docs/5.3/blade#displaying-data), so I am wondering why the error shows up. I will look into this somewhere next week.

**Comment by fryiee** [comment] 2016-12-01 13:29
I think it may be related to a Laravel package update.

**Comment by jeroennoten** [comment] 2016-12-05 20:22
I cannot reproduce this error. Can you try to run:

```
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets --force
```

**Comment by jeroennoten** [comment] 2016-12-08 08:12
I'll close this for now. Let me know if it needs to be reopened.

**Closed by jeroennoten** 2016-12-08 08:12 UTC

**Comment by robertheath** [comment] 2018-09-07 17:29
I know this is an old thread, but I had to change the "or" to "??"... I'm running Laravel 5.7 on PHP 7

**Comment by jefetiepo** [comment] 2018-09-07 23:41
I have the same problem here. I'm using php 7.2.9 and Laravel 5.7. I tried the solution proposed by @fryiee but it did not work for me. I'm newbie, is my first instalation, and I can do something wrong.

**Comment by edwardbreedveld** [comment] 2018-09-09 09:50
Same problem here with 5.7

**Comment by Lucky-Loek** [comment] 2018-09-09 09:57
This is addressed in #244

**Comment by edwardbreedveld** [comment] 2018-09-09 09:59
fixed with #244

**Comment by digitalprored** [comment] 2018-09-12 07:28
Hello. Same error again.

New install:
- Laravel 5.7.2
- Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips 
- PHP/7.2.5

ErrorException (E_ERROR)
Undefined index: icon (View: /var/.../vendor/jeroennoten/laravel-adminlte/resources/views/partials/menu-item.blade.php)

            <i class="fa fa-fw fa-<?php echo e($item['icon'] **or** 'circle-o'); ?> <?php echo e(isset($item['icon_color']) ? 'text-' . $item['icon_color'] : ''); ?>"></i>**

**Comment by vatraiadarsh** [comment] 2018-09-16 05:16
same issue with laravel 5.7

**Comment by carloshperes** [comment] 2018-09-16 14:06
@Rodrigusto solutions works for me

**Comment by tailivan** [comment] 2018-09-20 09:35
solutions works for me
