### ISSUE TITLE
"Undefined constant 'JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper' (View: C:\laragon\www\kors\vendor\jeroennoten\laravel-adminlte\resources\views\page.blade.php)"

### ISSUE THREAD

**Issue by ferchivilcoy** [jeroennoten/Laravel-AdminLTE#812] opened 2021-02-23 21:30 UTC
|After installing the ADMINLTE package, I get the following error when I want to use it in any view
"Undefined constant 'JeroenNoten \ LaravelAdminLte \ Helpers \ LayoutHelper' (View: C: \ laragon \ www \ kors \ vendor \ jeroennoten \ laravel-adminlte \ resources \ views \ page.blade.php)"

What could it be ?, Until yesterday it worked perfect for me

**Comment by Shidersz** [comment] 2021-02-23 21:37
@ferchivilcoy I have also notice this, I will upload a PR soon for this issue. What version of Laravel are you running? In my particular case this happens after updating **laravel/framework** to **8.29.0**.

**Comment by ferchivilcoy** [comment] 2021-02-23 21:45
Today I did a new Laravel installation and I have 8.29.0 too. We will have to wait for that bug to be corrected..

**Comment by alek10c** [comment] 2021-02-23 21:48
same error for my use laravel 8.12

**Comment by alek10c** [comment] 2021-02-23 21:50
I just did a clean install and this error occurs. Sad.

**Comment by Alex0Fury** [comment] 2021-02-23 23:13
I managed to solve the problem, but I don't know how much is correct.
My solution is in the files :

> resources/views/vendor/adminlte/partials/sidebar/menu-item.blade.php
> resources/views/vendor/adminlte/partials/navbar/menu-item.blade.php

I refactor @inject('menuItemHelper', '\JeroenNoten\LaravelAdminLte\Helpers\MenuItemHelper')
and all files, where strict this error

because name space  \JeroenNoten\LaravelAdminLte\Helpers\MenuItemHelper you need to enclose it in quotation marks

sees an undefined constant, instead of the path to the helper

I hope this helps you

**Comment by ferchivilcoy** [comment] 2021-02-23 23:55
Alex0Fury 

I tried to do what you say, but it still doesn't work ..

**Comment by Alex0Fury** [comment] 2021-02-24 00:00
> Alex0Fury
> 
> Я пытался сделать то, что вы говорите, но все равно не работает ...
your refactor
C: \ laragon \ www \ kors \ vendor \ jeroennoten \ laravel-adminlte \ resources \ views \ page.blade.php

in page.blade.php refactor @inject('layoutHelper', 'JeroenNoten \ LaravelAdminLte \ Helpers \ LayoutHelper')

and you will have a new error, only in a different file

**Comment by Shidersz** [comment] 2021-02-24 02:37
@Alex0Fury thanks for the feedback. To manually solve this issue (while waiting for a new release) check PR #813 to see what files you need to change.
If you have [plublished the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/11.-Customize-Views) then you need to edit files inside `resources/views/vendor/adminlte/`.
Otherwise you need to edit files in `vendor/jeroennoten/laravel-adminlte/resources/views/`.
Paths are relative to your Laravel project.

> **Important:** After the new release, you will need to manually update the views you have previously published (if this is your case).

**Comment by resslinger** [comment] 2021-02-24 11:14
The fix was released with v3.5.3.

**Comment by DesarrolloProm** [comment] 2021-02-24 15:09
This helps to solve that, but idk if it´s because of this that a "bug" happens, it's just that if one of your sidebar options has two words it disappears. 
![Captura](https://user-images.githubusercontent.com/75850851/109020869-fc416380-767f-11eb-8e70-05d2500a44c3.PNG)
![Captura1](https://user-images.githubusercontent.com/75850851/109020885-ff3c5400-767f-11eb-8e2c-bd9868954d74.PNG)

**Comment by Shidersz** [comment] 2021-02-24 17:09
@DesarrolloProm The solved issue was about injecting a service into the blade views, should not be related to your problem. I will check your configuration to see if I can reproduce the problem.

**Comment by Shidersz** [comment] 2021-02-24 18:41
@DesarrolloProm Can't reproduce your issue. Please, consider opening a new issue adding all the information to reproduce the issue, like:

- The complete menu configuration on `adminlte.php` file.
- The locale you are using (this is configured on the laravel file `config/app.php`).
- The package translation files for the locale setup. For example `resources/lang/vendor/adminlte/en/` if locale is configured to `en`.
- Other data you consider is important.

**Comment by DesarrolloProm** [comment] 2021-02-24 20:16
@Shidersz I just rewrite the options names and everything's fine again, maybe it's just something on my cpanel or hosting idk.

**Comment by asartz** [comment] 2021-02-28 09:21
Could you please also merge the fix into the next branch?

**Comment by Shidersz** [comment] 2021-03-01 21:15
@asartz You can do it yourself on your local environment, take a look to this [Stackoverflow Question](https://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch). The `next` branch is not official, it is just used to develop and test the new components that will come on next package versions.

**Comment by Puduru** [comment] 2021-03-19 01:37
> The fix was released with v3.5.3.

The problem wasn't fixed in `vendor/jeroennoten/laravel-adminlte/resources/views/partials/common/brand-logo-xl.blade.php`.

**Comment by Shidersz** [comment] 2021-03-19 02:13
@Puduru thank you for your feedback. A **Pull Request** was created for it...

**Closed** 2021-03-19 14:00 UTC
Labels: bug, scheduled

**Comment by Dev96xp** [comment] 2022-02-08 06:17
I got this after $ composer update, any solution

Error
Undefined constant "JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper" (View: C:\xampp\htdocs\codersfree\resources\views\vendor\adminlte\page.blade.php)

**Comment by resslinger** [comment] 2022-02-08 07:49
@Dev96xp Please provide us with more details like version of this plugin & laravel version. Thank you.

**Comment by lukaskukla** [comment] 2022-02-08 09:12
I have the same error message:

```
lluminate\View\ViewException · Undefined constant 'JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper' (View: /home/forge/xxx/resources/views/vendor/adminlte/page.blade.php) (View: /home/forge/xxx/resources/views/vendor/adminlte/page.blade.php)
```

Laravel Version: v8.76.2
Laravel Adminlte Version: v3.7.2

**Comment by rightwayround** [comment] 2022-02-08 09:44
Try running `artisan view:clear`

**Comment by lukaskukla** [comment] 2022-02-08 09:52
> Try running `artisan view:clear`

Didn't work for me. Tried also to clear cache etc. and upgraded to version `v3.7.3`

**Comment by Dev96xp** [comment] 2022-02-08 10:18
Everything was working fine, until I did the composer update ($ composer update), once I finished, I tried to enter my app, where I use LTEADMIN, it won't let me enter anymore and I get this error.

Error
Undefined constant "JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper" (View: C:\xampp\htdocs\codersfree\resources\views\vendor\adminlte\page.blade.php)

I have this:

$ php artisan --version
Laravel Framework 8.82.0


![image](https://user-images.githubusercontent.com/62994991/152964283-20d14739-6e8f-4f05-a9d2-3cbfcf93b806.png)

**Comment by Shidersz** [comment] 2022-02-08 13:04
@lukaskukla @Dev96xp Your problem is mainly because you have published the views but you have never updated they. I recommend to to compare folders `resources/views/vendor/adminlte` with `vendor/jeroennoten/laravel-adminlte/resources/views/` and add all the changes you see on the second one to the first one. You may also follow the [update procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) mentioned on the Wiki pages (**check step 3**).

**Comment by Dev96xp** [comment] 2022-02-08 21:23
OMG,..Works..Thank you very much, work, I made the backups of those two folders and then execute the command from step 3, which you sent me and work is fixed, thank you very much !!!
I backup these
![image](https://user-images.githubusercontent.com/62994991/153077446-29071f83-2910-4674-aebb-3ca59c778bfd.png)
![image](https://user-images.githubusercontent.com/62994991/153077489-febe09b7-de42-47f1-a9a4-c695a9b3a65c.png)

and 
![image](https://user-images.githubusercontent.com/62994991/153077394-e0ef05bc-bdfe-495b-ab43-821d41960eb1.png)

$ php artisan adminlte:install --only=main_views --force

@lukaskukla thank you very much !!!

**Comment by Dev96xp** [comment] 2022-02-10 03:22
Diego Smania, thank you so much, [shidersz@hotmail.com](mailto:shidersz@hotmail.com)

**Comment by Dev96xp** [comment] 2022-02-10 03:22
@Shidersz, Thank you so much for your help!

**Comment by Dev96xp** [comment] 2022-02-10 07:49
@Shidersz,

I just found that this button does not work, I press it and it does absolutely nothing, it is inside a livewire component, I had not touched it at all but it works perfectly I don't know if it is related to the previous error, any solution in mind?

![image](https://user-images.githubusercontent.com/62994991/153361316-745934ff-6296-403b-8491-6aac15b1d499.png)

thank you.

**Comment by Dev96xp** [comment] 2022-02-10 09:15
I just realized that my livewire components stopped working inside Laravel-AdminLTE, I try these components on other pages and they work fine, any suggestion, this happened after I resolved the above error from: (JeroenNoten\LaravelAdminLte....)  thank you.

**Comment by Shidersz** [comment] 2022-02-10 12:57
@Dev96xp Should not be related to the previous problem, make a comparison between your backups views and the ones currently published. Maybe you made a custom change on the past...
