### ISSUE TITLE
[BUG] Blade components does not work 

### ISSUE THREAD

**Issue by joaonivaldo** [jeroennoten/Laravel-AdminLTE#870] opened 2021-04-22 01:33 UTC
### Describe the bug
I just installed the latest version of your package. But I can't open any component, they all give an error not found.
Ex. When I call the alert like this:
<x-adminlte-alert> Minimal example </x-adminlte-alert>
give this error:
Unable to locate a class or view for component [adminlte-alert].

This is happening with all the components I test.

Do you have to do something to be able to use them?

Thanks

### Screenshots
If applicable, add screenshots to help explain your problem or to shown the issue.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 8.12
| Project | 3.5.4
| OS      | Windows

### Additional context
Add any other context about the problem here. If you already have ideas to solve the issue, add them here or create a Pull Request (PR).

**Comment by Shidersz** [comment] 2021-04-22 04:36
@joaonivaldo  There is no official release with components. They are under development, on the final stage, and we hope to release they soon. Duplicate of #866

**Comment by Shidersz** [comment] 2021-04-23 21:55
Components will be available for package version **v3.6.0** or greater.

**Closed by Shidersz** 2021-04-23 21:55 UTC
Labels: duplicate
